### ISSUE TITLE
Uncaught TypeError: this.pane.onDidChangePath is not a function

### ISSUE THREAD

**Issue by alk-jerber** [Connormiha/atom-tab-foldername-index#1]
[Enter steps to reproduce below:]

1. open an image file (PNG)

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [tab-foldername-index](https://github.com/Connormiha/atom-tab-foldername-index) package, v1.0.1

### Stack Trace

Uncaught TypeError: this.pane.onDidChangePath is not a function

```
At /Users/Topper/.atom/packages/tab-foldername-index/lib/tab.js:56

TypeError: this.pane.onDidChangePath is not a function
    at new Tab (/Users/Topper/.atom/packages/tab-foldername-index/lib/tab.js:56:39)
    at Object.addTab (/Users/Topper/.atom/packages/tab-foldername-index/lib/main.js:73:30)
    at realTimeout (/Users/Topper/.atom/packages/tab-foldername-index/lib/main.js:46:36)
```

### Commands

```
     -1:08.2.0 project-find:show (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:08.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  7x -1:03.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -1:01.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:58.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:58 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:58 blur (atom-text-editor.editor.mini.is-focused)
  4x -0:56.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:55.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:55.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:47 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -0:47 blur (atom-text-editor.editor.mini.is-focused)
     -0:43 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:12.3.0 tree-view:reveal-active-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 10x -0:12.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "logo-file-icons",
      "file-type-icons",
      "language-gfm",
      "nice-index",
      "whitespace"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
afterglow-like, v0.2.1 (inactive)
afterglow-monokai-syntax, v1.3.4 (inactive)
afterglow-plus, v1.6.0 (inactive)
atom-beautify, v0.29.13 (active)
atom-handlebars, v1.3.0 (active)
autocomplete-paths, v1.0.2 (active)
cucumber, v0.5.0 (active)
editorconfig, v2.0.5 (active)
emmet, v2.4.3 (active)
ex-mode, v0.13.1 (inactive)
ex-mode-sort, v1.0.0 (active)
file-icons, v1.7.25 (active)
goto, v1.7.1 (inactive)
highlight-selected, v0.11.2 (active)
language-babel, v2.48.5 (active)
language-gherkin, v1.0.4 (active)
language-groovy, v0.6.0 (active)
language-markdown, v0.18.1 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
minimap, v4.25.6 (active)
open-this, v0.3.0 (inactive)
pretty-json, v1.6.1 (active)
project-view, v0.6.1 (active)
sort-lines, v0.14.0 (inactive)
tab-foldername-index, v1.0.1 (active)
tree-view-git-status, v1.2.0 (active)
vim-mode, v0.65.1 (active)
vim-surround, v0.8.1 (active)
webbox-color, v0.5.9 (active)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (active)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Connormiha** [comment]
Thanks for your report. This bug will be fixed in next release in the near time.

**Comment by Connormiha** [comment]
Fixed
