### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by ghost** [Connormiha/atom-tab-foldername-index#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [tab-foldername-index](https://github.com/Connormiha/atom-tab-foldername-index) package 3.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/milesminton/.atom/packages/tab-foldername-index/lib/main.js:173

TypeError: Cannot read property 'add' of null
    at Object.addTab (/packages/tab-foldername-index/lib/main.js:173:32)
    at realTimeout (/packages/tab-foldername-index/lib/main.js:105:36)
```

### Commands

```
     -0:55.1.0 tree-view:collapse-directory (div.tool-panel.tree-view)
  4x -0:54.5.0 core:move-down (div.tool-panel.tree-view)
     -0:53.7.0 core:move-up (div.tool-panel.tree-view)
     -0:53.6.0 tree-view:collapse-directory (div.tool-panel.tree-view)
 15x -0:53.3.0 core:move-down (div.tool-panel.tree-view)
  8x -0:49.2.0 core:close (input.hidden-input)
     -0:46.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
 31x -0:46.4.0 core:move-down (div.tool-panel.tree-view)
  5x -0:43.8.0 core:move-up (div.tool-panel.tree-view)
     -0:38.5.0 tree-view:reveal-active-file (div.tool-panel.tree-view)
  5x -0:37.8.0 core:move-down (div.tool-panel.tree-view)
     -0:36.5.0 tree-view:open-selected-entry (div.tool-panel.tree-view)
  2x -0:21.1.0 core:move-up (div.tool-panel.tree-view)
  3x -0:20.1.0 core:move-down (div.tool-panel.tree-view)
     -0:16.3.0 core:close (input.hidden-input)
     -0:03.7.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
<list suppressed>
```

**Comment by Connormiha** [comment]
@minton1 thx for your request. I released new `3.3.2` version. This problem should be fixed.
