### ISSUE TITLE
Uncaught TypeError: pane.onDidDestroy is not a function

### ISSUE THREAD

**Issue by sergop321** [Connormiha/atom-tab-foldername-index#4]
**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [tab-foldername-index](https://github.com/Connormiha/atom-tab-foldername-index) package 2.0.2

### Stack Trace

Uncaught TypeError: pane.onDidDestroy is not a function

```
At /Users/sergo/.atom/packages/tab-foldername-index/lib/main.js:124

TypeError: pane.onDidDestroy is not a function
  at Object.addTab (/packages/tab-foldername-index/lib/main.js:124:30)
  at realTimeout (/packages/tab-foldername-index/lib/main.js:70:36)

```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.1 
es6-javascript 1.0.0 
file-icons 2.1.4 
git-plus 7.7.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.58.0 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.4 
linter-eslint 8.1.7 
linter-ui-default 1.2.3 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.222.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tab-foldername-index 2.0.2 
tool-bar 1.1.0 
```

**Comment by Connormiha** [comment]
@sergop321 
How can i do repeat this bug? Could you explain about your steps, please.

**Comment by sergop321** [comment]
It happens every time I do a package update and than atom ask to restart itself, after the restart I see this error.

**Comment by Connormiha** [comment]
With release 2.0.3 it should be fixed
